### ISSUE TITLE
Error on YARN add

### ISSUE THREAD

**Issue by levindoneto** [Wolox/react-chat-widget#247] opened 2021-03-29 05:49 UTC
I get this when I run `yarn add react-chat-widget`:

```
warning rasa-webchat > socket.io > engine.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
[2/4] Fetching packages...
error https://registry.yarnpkg.com/workbox-sw/-/workbox-sw-5.1.4.tgz: Integrity check failed for "workbox-sw" (computed integrity doesn't match our records, got "sha512-9xKnKw95aXwSNc8kk8gki4HU0g0W6KXu+xks7wFuC7h0sembFnTrKtckqZxbSod41TDaGh+gWUA5IRXrL0ECRA== sha1-K7NMn3OB+Q2EzvZEgW1FFQAR09s=")
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by CrisVega08** [comment] 2021-05-14 18:00
Hi @levindoneto thanks for reporting this issue but we couldn't reproduce the error., can you give us more context about environment used?

**Comment by CrisVega08** [comment] 2021-06-04 19:25
We are going to close this issue, we couldn't reproduce.

**Closed by CrisVega08** 2021-06-04 19:25 UTC
